version: '3.9'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5434:5432 #{host(myPC)}:{container}
    #environment variables for postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - nestjs-framework
networks:
  nestjs-framework: 

#docker compose up -d
#docker compose up -d dev-database -d
#docker compose down
#docker compose rm dev-database --stop --force --volumes